// Copyright (c) 2026 DOMINGUEZ Vincent
// Licensed under the DOMINGUEZ Non-Commercial Software License v1.0.
// See LICENSE for details.

#include "ui/EmbeddedAssets.hpp"

#include <array>

namespace px::assets {

namespace {

// Generated byte payload is isolated from the asset access API.
constexpr std::array<unsigned char, 10951> kSplashPng = {
#include "details/EmbeddedSplashPngData.inc"
};

} // namespace

std::span<const unsigned char> splash_png() noexcept {
    return kSplashPng;
}

} // namespace px::assets
